name: Finlogger CI

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches: [ main, back ]
  pull_request:
    branches: [ main, back ]
  workflow_dispatch:

jobs:
  test-back:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          CI: true


